-- =============================================================
-- SEED: Documents & Services publics de Kinshasa
-- Comprehensive reference: definitions, prix, procédures
-- =============================================================

-- ===================== ÉTAT CIVIL =====================

INSERT INTO documents (id, nom, slug, categorie, description, definition, role, prix_estimatif, devise, delai_estimatif, documents_requis, procedure, ou_obtenir, conseils, base_juridique, aliases, actif, created_at, updated_at) VALUES

(gen_random_uuid(), 'Acte de naissance', 'acte-de-naissance', 'ETAT_CIVIL',
 'Document officiel attestant la naissance d''une personne.',
 'L''acte de naissance est un document d''état civil qui enregistre officiellement la naissance d''un enfant. Il mentionne le nom, le sexe, la date et le lieu de naissance, ainsi que les noms des parents.',
 'Indispensable pour toute démarche administrative : inscription scolaire, obtention de carte d''identité, passeport, mariage, succession.',
 5000, 'FC', '3 à 7 jours ouvrables',
 ARRAY['Attestation de naissance de la maternité', 'Carte d''identité des parents', 'Livret de ménage des parents'],
 '1. Se rendre au bureau d''état civil de la commune de naissance\n2. Présenter l''attestation de naissance de la maternité\n3. Fournir les pièces d''identité des parents\n4. Payer les frais officiels\n5. Retirer l''acte après le délai indiqué',
 'Bureau d''état civil de la maison communale de la commune de naissance',
 'Déclarer la naissance dans les 90 jours. Au-delà, un jugement supplétif est nécessaire. Vérifier que tous les noms sont correctement orthographiés avant de quitter le bureau.',
 'Loi n° 16/008 du 15 juillet 2016 modifiant la loi n° 87-010 portant Code de la famille',
 ARRAY['acte naissance', 'extrait naissance', 'certificat naissance', 'birth certificate', 'naissance'], true, NOW(), NOW()),

(gen_random_uuid(), 'Acte de mariage', 'acte-de-mariage', 'ETAT_CIVIL',
 'Document officiel attestant l''union matrimoniale entre deux personnes.',
 'L''acte de mariage est un document d''état civil qui enregistre l''union légale entre deux époux devant l''officier d''état civil.',
 'Prouve le statut matrimonial. Nécessaire pour les démarches de regroupement familial, succession, pension.',
 15000, 'FC', '1 à 2 semaines',
 ARRAY['Acte de naissance de chaque époux', 'Carte d''identité des époux', 'Certificat de célibat ou de coutume', 'Photos d''identité (4 par personne)', 'Témoins (2 minimum) avec leurs pièces d''identité', 'Dot payée (attestation coutumière)'],
 '1. Retirer et remplir le formulaire au bureau d''état civil\n2. Déposer les dossiers des deux époux\n3. Publication des bans (15 jours)\n4. Célébration du mariage devant l''officier d''état civil\n5. Retrait de l''acte de mariage',
 'Bureau d''état civil de la maison communale',
 'Le mariage coutumier seul n''a pas de valeur légale complète. Enregistrer le mariage à l''état civil pour une protection juridique complète.',
 'Code de la Famille, Livre II',
 ARRAY['mariage', 'acte mariage', 'marriage certificate', 'union', 'se marier'], true, NOW(), NOW()),

(gen_random_uuid(), 'Acte de décès', 'acte-de-deces', 'ETAT_CIVIL',
 'Document officiel attestant le décès d''une personne.',
 'L''acte de décès est un document d''état civil qui enregistre officiellement la mort d''une personne, avec la date, le lieu et la cause du décès.',
 'Obligatoire pour la succession, le transfert de propriété, la pension de veuvage, la radiation des registres.',
 5000, 'FC', '3 à 5 jours ouvrables',
 ARRAY['Attestation de décès de l''hôpital ou médecin', 'Carte d''identité du défunt', 'Carte d''identité du déclarant', 'Livret de ménage'],
 '1. Obtenir l''attestation de décès du médecin/hôpital\n2. Se rendre à l''état civil de la commune du décès\n3. Présenter les documents requis\n4. Payer les frais\n5. Retirer l''acte de décès',
 'Bureau d''état civil de la commune où le décès a eu lieu',
 'Déclarer le décès dans les 30 jours. Conserver plusieurs copies de l''acte pour les différentes démarches de succession.',
 'Code de la Famille, Titre II',
 ARRAY['deces', 'décès', 'acte deces', 'death certificate', 'mort', 'certificat deces'], true, NOW(), NOW()),

(gen_random_uuid(), 'Certificat de célibat', 'certificat-de-celibat', 'ETAT_CIVIL',
 'Attestation prouvant qu''une personne n''est pas mariée.',
 'Le certificat de célibat est un document délivré par l''officier d''état civil attestant qu''une personne n''a contracté aucun mariage civil.',
 'Requis pour le mariage civil, certaines démarches d''immigration et adoptions.',
 3000, 'FC', '1 à 3 jours',
 ARRAY['Carte d''identité', 'Acte de naissance'],
 '1. Se présenter au bureau d''état civil\n2. Fournir la carte d''identité et l''acte de naissance\n3. Payer les frais\n4. Retirer le certificat',
 'Bureau d''état civil de la commune de résidence',
 'Vérifier la durée de validité exigée par l''institution demandeuse (généralement 3 mois).',
 NULL,
 ARRAY['celibat', 'célibat', 'single certificate', 'non marie', 'non marié'], true, NOW(), NOW()),

(gen_random_uuid(), 'Livret de ménage', 'livret-de-menage', 'ETAT_CIVIL',
 'Document familial regroupant les informations sur tous les membres d''un foyer.',
 'Le livret de ménage est le document officiel qui identifie un ménage et recense tous ses membres (chef de ménage, époux/épouse, enfants, dépendants).',
 'Sert de document d''identification familiale. Requis pour l''inscription scolaire des enfants, les démarches administratives, le recensement.',
 10000, 'FC', '5 à 10 jours',
 ARRAY['Carte d''identité du chef de ménage', 'Acte de mariage', 'Actes de naissance des enfants', 'Attestation de résidence'],
 '1. Se rendre à la maison communale de résidence\n2. Présenter les documents requis\n3. Payer les frais\n4. Un agent vérifie l''adresse (visite optionnelle)\n5. Retirer le livret de ménage',
 'Bureau du chef de quartier puis maison communale',
 'Mettre à jour le livret de ménage à chaque naissance, décès ou changement de résidence.',
 NULL,
 ARRAY['livret menage', 'fiche menage', 'household book', 'famille'], true, NOW(), NOW()),

(gen_random_uuid(), 'Attestation de résidence', 'attestation-de-residence', 'ETAT_CIVIL',
 'Document certifiant qu''une personne réside à une adresse donnée.',
 'L''attestation de résidence est délivrée par le chef de quartier et confirmée par la commune, certifiant le domicile d''un résident.',
 'Nécessaire pour l''inscription scolaire, l''ouverture de compte bancaire, les démarches judiciaires, le livret de ménage.',
 2000, 'FC', '1 à 2 jours',
 ARRAY['Carte d''identité', 'Livret de ménage (si disponible)'],
 '1. Se rendre chez le chef de quartier\n2. Obtenir la signature du chef de quartier\n3. Se rendre à la maison communale pour validation\n4. Payer les frais\n5. Retirer l''attestation',
 'Bureau du chef de quartier, validé à la maison communale',
 'Demander au chef de quartier en premier. La commune ne fait que valider.',
 NULL,
 ARRAY['residence', 'résidence', 'attestation residence', 'domicile', 'adresse'], true, NOW(), NOW()),

(gen_random_uuid(), 'Jugement supplétif d''acte de naissance', 'jugement-suppletif-naissance', 'ETAT_CIVIL',
 'Décision judiciaire remplaçant un acte de naissance non enregistré dans les délais.',
 'Le jugement supplétif est une décision du tribunal de paix qui tient lieu d''acte de naissance lorsque la déclaration n''a pas été faite dans le délai légal de 90 jours.',
 'Permet d''obtenir un acte de naissance tardif pour toute personne dont la naissance n''a pas été déclarée à temps.',
 25000, 'FC', '2 à 4 semaines',
 ARRAY['Attestation de naissance de la maternité (si disponible)', 'Carte d''identité des parents', 'Deux témoins avec pièce d''identité', 'Requête adressée au tribunal de paix'],
 '1. Rédiger une requête au tribunal de paix\n2. Joindre tous les documents disponibles\n3. Payer les frais de justice\n4. Comparaître devant le juge avec les témoins\n5. Après prononcé du jugement, faire transcrire à l''état civil',
 'Tribunal de paix de la commune de naissance',
 'Procédure plus longue et coûteuse que la déclaration normale. Déclarer les naissances à temps pour éviter ce processus.',
 'Code de la Famille, article 116',
 ARRAY['jugement suppletif', 'suppletif', 'naissance tardive', 'acte tardif'], true, NOW(), NOW()),

-- ===================== FONCIER / PARCELLE =====================

(gen_random_uuid(), 'Livret parcellaire (certificat d''enregistrement)', 'livret-parcellaire', 'IMPOTS',
 'Document officiel prouvant le droit de jouissance sur une parcelle de terrain.',
 'Le livret parcellaire (ou certificat d''enregistrement) est le titre foncier qui atteste du droit de concession perpétuelle ou ordinaire sur une parcelle. C''est le document final qui prouve la propriété.',
 'Preuve légale de propriété foncière. Protège contre les litiges fonciers, les doubles ventes, et l''expropriation illégale.',
 250000, 'FC', '3 à 6 mois',
 ARRAY['Contrat de vente notarié', 'Certificat de vacance parcellaire', 'Procès-verbal de mesurage (croquis)', 'Fiche parcellaire du quartier', 'Carte d''identité de l''acquéreur', 'Quittance de paiement des taxes foncières'],
 '1. Achat et signature du contrat de vente chez un notaire\n2. Obtenir la fiche parcellaire auprès du chef de quartier/commune\n3. Demander le certificat de vacance au bureau du cadastre\n4. Faire effectuer le mesurage par un géomètre agréé\n5. Déposer le dossier au bureau de la Conservation des titres immobiliers\n6. Payer les frais d''enregistrement\n7. Retirer le livret parcellaire après traitement',
 'Bureau de la Conservation des Titres Immobiliers (Cadastre), Ministère des Affaires Foncières',
 'NE JAMAIS acheter une parcelle sans vérifier au cadastre si elle n''est pas déjà enregistrée au nom d''un autre. Exiger un contrat notarié. Faire le mesurage avant le paiement complet.',
 'Loi n° 73-021 du 20 juillet 1973 portant régime général des biens, régime foncier et immobilier',
 ARRAY['parcelle', 'livret parcellaire', 'certificat enregistrement', 'terrain', 'achat parcelle', 'acheter parcelle', 'titre foncier', 'propriete', 'propriété', 'concession'], true, NOW(), NOW()),

(gen_random_uuid(), 'Certificat de vacance parcellaire', 'certificat-vacance-parcellaire', 'IMPOTS',
 'Attestation confirmant qu''une parcelle n''est pas occupée ni enregistrée au nom d''un tiers.',
 'Le certificat de vacance est délivré par le service du cadastre pour confirmer qu''un terrain est juridiquement disponible et n''appartient à aucune autre personne.',
 'Étape indispensable avant l''achat d''une parcelle. Protège l''acheteur contre les doubles attributions.',
 50000, 'FC', '1 à 3 semaines',
 ARRAY['Demande adressée au conservateur des titres', 'Indication de la localisation exacte de la parcelle', 'Reçu de paiement des frais'],
 '1. Se rendre au bureau du cadastre de la commune\n2. Formuler une demande écrite de vérification\n3. Payer les frais de recherche\n4. Le service vérifie dans ses registres\n5. Retirer le certificat de vacance',
 'Bureau du Cadastre / Conservation des Titres Immobiliers',
 'Exiger ce certificat AVANT tout paiement au vendeur. C''est la première étape.',
 NULL,
 ARRAY['vacance parcellaire', 'vacance', 'verification parcelle', 'cadastre verification'], true, NOW(), NOW()),

(gen_random_uuid(), 'Contrat de vente notarié', 'contrat-vente-notarie', 'JUSTICE',
 'Acte authentique de vente immobilière rédigé et certifié par un notaire.',
 'Le contrat de vente notarié est un acte authentique qui matérialise le transfert de propriété (ou de droit de jouissance) d''un bien immobilier entre le vendeur et l''acheteur.',
 'Donne valeur juridique à la transaction immobilière. Obligatoire pour l''obtention du livret parcellaire.',
 100000, 'FC', '1 à 2 semaines',
 ARRAY['Carte d''identité de l''acheteur et du vendeur', 'Titre foncier du vendeur (livret parcellaire)', 'Certificat de vacance parcellaire', 'Accord de prix entre les parties'],
 '1. Choisir un notaire agréé\n2. Réunir toutes les pièces du vendeur et de l''acheteur\n3. Le notaire rédige le contrat\n4. Lecture et signature par les deux parties\n5. Payer les frais du notaire (généralement 3-5% du prix)\n6. Le notaire délivre une expédition du contrat',
 'Étude notariale / Notaire public',
 'N''utiliser que des notaires agréés. Vérifier les références du notaire auprès du barreau.',
 'Code civil congolais, Livre III',
 ARRAY['contrat vente', 'vente notaire', 'acte vente', 'notaire', 'acte notarie', 'acte notarié'], true, NOW(), NOW()),

(gen_random_uuid(), 'Procès-verbal de mesurage (croquis)', 'proces-verbal-mesurage', 'IMPOTS',
 'Document technique établissant les dimensions exactes et les limites d''une parcelle.',
 'Le PV de mesurage est le document établi par un géomètre assermenté du cadastre qui fixe les limites exactes d''une parcelle avec ses dimensions, superficie et coordonnées.',
 'Étape technique obligatoire avant l''enregistrement foncier. Permet de déterminer les limites précises du terrain.',
 75000, 'FC', '1 à 4 semaines',
 ARRAY['Certificat de vacance parcellaire', 'Contrat de vente', 'Demande de mesurage adressée au cadastre'],
 '1. Adresser une demande de mesurage au bureau du cadastre\n2. Payer les frais de mesurage\n3. Un géomètre se déplace sur le terrain\n4. Il procède au bornage et au mesurage\n5. Le PV est rédigé avec le croquis\n6. Retirer le document au bureau du cadastre',
 'Bureau du Cadastre — Service des mensurations',
 'Être présent lors du mesurage avec les voisins pour éviter les contestations de limites.',
 NULL,
 ARRAY['mesurage', 'croquis', 'geometre', 'géomètre', 'bornage', 'arpentage', 'cadastre mesurage'], true, NOW(), NOW()),

-- ===================== IDENTITÉ & VOYAGE =====================

(gen_random_uuid(), 'Carte d''identité nationale', 'carte-identite', 'ETAT_CIVIL',
 'Document d''identification officiel pour tout citoyen congolais.',
 'La carte d''identité est le document officiel qui permet d''identifier tout citoyen congolais majeur (18 ans et plus). Elle contient le nom, la photo, la date de naissance et l''adresse.',
 'Obligatoire pour toute démarche administrative, vote, ouverture de compte bancaire, voyage intérieur, emploi.',
 15000, 'FC', '2 à 4 semaines',
 ARRAY['Acte de naissance ou jugement supplétif', 'Attestation de résidence', '4 photos d''identité format passeport', 'Ancien document d''identité (si renouvellement)'],
 '1. Se rendre au bureau de l''état civil ou au centre d''enrôlement\n2. Présenter les documents requis\n3. Prise d''empreintes et de photo\n4. Payer les frais\n5. Retirer la carte après traitement',
 'Centre d''enrôlement / Bureau communal d''état civil',
 'Vérifier que tous les noms et dates sont corrects avant validation. Conserver une photocopie.',
 'Loi électorale et dispositions de l''ONIP',
 ARRAY['carte identite', 'carte identité', 'carte d identite', 'CI', 'identite', 'identité', 'ID card', 'piece identite', 'pièce identité'], true, NOW(), NOW()),

(gen_random_uuid(), 'Passeport congolais', 'passeport', 'ETAT_CIVIL',
 'Document de voyage international pour les citoyens de la RDC.',
 'Le passeport est un document officiel de voyage délivré par la Direction Générale de Migration (DGM) permettant au citoyen congolais de voyager à l''international.',
 'Obligatoire pour tout voyage international. Sert aussi de pièce d''identité officielle.',
 205, 'USD', '2 à 6 semaines',
 ARRAY['Acte de naissance', 'Carte d''identité ou carte d''électeur', 'Attestation de résidence', '4 photos d''identité biométriques', 'Ancien passeport (si renouvellement)', 'Formulaire de demande rempli'],
 '1. Retirer le formulaire à la DGM ou en ligne\n2. Remplir le formulaire\n3. Rassembler tous les documents\n4. Se présenter à la DGM avec les documents\n5. Prise de données biométriques\n6. Payer les frais ($205 USD pour le passeport ordinaire)\n7. Retirer le passeport après le délai',
 'Direction Générale de Migration (DGM), Avenue des Aviateurs, Gombe',
 'Faire la demande bien avant la date de voyage prévue. Le passeport semi-biométrique a une validité de 5 ans.',
 'Ordonnance-Loi n° 83-033 du 12 septembre 1983',
 ARRAY['passeport', 'passport', 'passe port', 'passe-port', 'travel document', 'voyage international', 'DGM', 'visa'], true, NOW(), NOW()),

(gen_random_uuid(), 'Visa de sortie', 'visa-de-sortie', 'ETAT_CIVIL',
 'Autorisation de quitter le territoire congolais.',
 'Le visa de sortie est un document délivré par la DGM autorisant un citoyen ou résident à quitter le territoire de la RDC.',
 'Obligatoire pour tout voyage international au départ de la RDC, en complément du passeport.',
 50, 'USD', '1 à 3 jours',
 ARRAY['Passeport valide', 'Billet d''avion', 'Visa du pays de destination (si applicable)'],
 '1. Se rendre à la DGM avec le passeport\n2. Présenter le billet d''avion\n3. Payer les frais de visa de sortie\n4. Le visa est apposé dans le passeport',
 'Direction Générale de Migration (DGM)',
 'Peut être obtenu le jour même en cas d''urgence. Prévoir ce coût dans le budget voyage.',
 NULL,
 ARRAY['visa sortie', 'sortie', 'quitter pays', 'exit visa'], true, NOW(), NOW()),

-- ===================== TRANSPORT / VÉHICULE =====================

(gen_random_uuid(), 'Immatriculation véhicule (plaque)', 'immatriculation-vehicule', 'TRANSPORT',
 'Obtention de la plaque d''immatriculation pour un véhicule.',
 'L''immatriculation est l''enregistrement officiel d''un véhicule auprès de la Direction Générale des Impôts (DGI), matérialisé par une plaque minéralogique.',
 'Obligatoire pour circuler légalement. Sert d''identification du véhicule et de son propriétaire.',
 150000, 'FC', '1 à 4 semaines',
 ARRAY['Carte grise originale ou certificat de dédouanement', 'Carte d''identité du propriétaire', 'Attestation d''assurance', 'Quittance de paiement de la taxe de circulation'],
 '1. Se rendre à la Direction des Recettes de Kinshasa (DGRK) ou DGI\n2. Présenter les documents du véhicule\n3. Payer les frais d''immatriculation\n4. Recevoir le numéro de plaque\n5. Faire fabriquer la plaque (atelier agréé)\n6. Retirer la carte d''immatriculation',
 'Direction Générale des Impôts (DGI) / DGRK',
 'Vérifier l''authenticité de la carte grise avant l''achat d''un véhicule.',
 NULL,
 ARRAY['immatriculation', 'plaque', 'matricule voiture', 'plaque voiture', 'enregistrement vehicule', 'enregistrement véhicule'], true, NOW(), NOW()),

(gen_random_uuid(), 'Vignette automobile', 'vignette-automobile', 'TRANSPORT',
 'Taxe annuelle obligatoire pour tout véhicule circulant à Kinshasa.',
 'La vignette est un timbre fiscal annuel attestant du paiement de la taxe de circulation. Elle doit être apposée sur le pare-brise du véhicule.',
 'Obligatoire pour circuler. Son absence entraîne des amendes et la mise en fourrière du véhicule.',
 60000, 'FC', 'Immédiat (après paiement)',
 ARRAY['Carte d''immatriculation du véhicule', 'Ancien vignette (si renouvellement)', 'Carte d''identité du propriétaire'],
 '1. Se rendre à la DGRK ou dans un bureau agréé\n2. Présenter la carte d''immatriculation\n3. Payer la taxe (montant varie selon le type de véhicule)\n4. Recevoir la vignette\n5. L''apposer sur le pare-brise',
 'Direction Générale des Recettes de Kinshasa (DGRK) / Bureaux de perception',
 'Renouveler chaque année au 1er janvier. Ne pas acheter de fausses vignettes — vérifier le sceau officiel.',
 NULL,
 ARRAY['vignette', 'vignette auto', 'taxe circulation', 'vignette voiture', 'taxe vehicule', 'taxe véhicule'], true, NOW(), NOW()),

(gen_random_uuid(), 'Permis de conduire', 'permis-de-conduire', 'TRANSPORT',
 'Autorisation officielle de conduire un véhicule motorisé.',
 'Le permis de conduire est un document officiel autorisant son titulaire à conduire un véhicule de la catégorie indiquée sur le territoire de la RDC.',
 'Obligatoire pour conduire tout véhicule motorisé. Requis par les forces de l''ordre lors des contrôles routiers.',
 50000, 'FC', '2 à 6 semaines',
 ARRAY['Carte d''identité', '4 photos d''identité', 'Certificat médical d''aptitude à la conduite', 'Attestation de réussite à l''examen de conduite', 'Ancien permis (si renouvellement)'],
 '1. S''inscrire dans une auto-école agréée\n2. Suivre la formation théorique et pratique\n3. Passer l''examen de conduite\n4. Obtenir l''attestation de réussite\n5. Se rendre au bureau des permis avec les documents\n6. Payer les frais\n7. Retirer le permis',
 'Commission provinciale des permis de conduire / Bureau des transports',
 'Les catégories de permis : A (moto), B (voiture), C (poids lourd), D (transport en commun). Renouveler tous les 5 ans.',
 NULL,
 ARRAY['permis conduire', 'permis', 'conduire', 'driving license', 'auto ecole', 'auto-école', 'examen conduite'], true, NOW(), NOW()),

(gen_random_uuid(), 'Assurance véhicule (carte jaune SONAS)', 'assurance-vehicule', 'TRANSPORT',
 'Assurance obligatoire de responsabilité civile automobile.',
 'L''assurance automobile (carte jaune SONAS) est l''assurance de responsabilité civile obligatoire couvrant les dommages causés à des tiers en cas d''accident.',
 'Obligatoire pour tout véhicule circulant en RDC. Protège financièrement en cas d''accident.',
 120, 'USD', 'Immédiat (après paiement)',
 ARRAY['Carte d''immatriculation du véhicule', 'Carte d''identité du propriétaire'],
 '1. Se rendre à une agence SONAS\n2. Présenter la carte d''immatriculation\n3. Choisir la formule d''assurance\n4. Payer la prime annuelle\n5. Recevoir la carte jaune d''assurance',
 'SONAS (Société Nationale d''Assurances) — agences dans chaque commune',
 'La carte jaune doit toujours être dans le véhicule. La SONAS est le seul assureur agréé en RDC.',
 'Ordonnance-Loi n° 66/622 du 23 novembre 1966',
 ARRAY['assurance', 'assurance voiture', 'carte jaune', 'SONAS', 'assurance auto', 'responsabilite civile', 'responsabilité civile'], true, NOW(), NOW()),

(gen_random_uuid(), 'Contrôle technique', 'controle-technique', 'TRANSPORT',
 'Inspection obligatoire de l''état mécanique du véhicule.',
 'Le contrôle technique est une vérification périodique de l''état de fonctionnement et de sécurité d''un véhicule, effectuée par un centre agréé.',
 'Obligatoire pour la vignette et l''assurance. Garantit que le véhicule est en état de rouler.',
 30000, 'FC', 'Immédiat (1-2 heures)',
 ARRAY['Carte d''immatriculation', 'Ancien certificat de contrôle technique (si renouvellement)'],
 '1. Se rendre dans un centre de contrôle technique agréé\n2. Présenter le véhicule et la carte d''immatriculation\n3. Le technicien inspecte le véhicule\n4. Payer les frais\n5. Si le véhicule passe, recevoir le certificat',
 'Centres de contrôle technique agréés (ex: TRANSCOM)',
 'Faire le contrôle technique AVANT de renouveler la vignette. Vérifier les freins, phares et pneus avant l''inspection.',
 NULL,
 ARRAY['controle technique', 'contrôle technique', 'inspection vehicule', 'inspection véhicule', 'visite technique'], true, NOW(), NOW()),

-- ===================== SANTÉ =====================

(gen_random_uuid(), 'Carte de vaccination', 'carte-de-vaccination', 'SANTE',
 'Carnet enregistrant tous les vaccins reçus par une personne.',
 'La carte de vaccination (carnet de vaccination) est un document médical qui enregistre tous les vaccins administrés à une personne, avec les dates et les rappels.',
 'Obligatoire pour les enfants (inscription scolaire). Requis pour le voyage international (fièvre jaune). Suivi médical vaccinal.',
 5000, 'FC', 'Immédiat',
 ARRAY['Carte d''identité ou acte de naissance (pour enfant)'],
 '1. Se présenter au centre de santé ou hôpital\n2. Demander la vaccination souhaitée\n3. Le carnet est rempli à chaque vaccination\n4. Pour les enfants : suivre le calendrier du PEV',
 'Centres de santé, hôpitaux, Programme Élargi de Vaccination (PEV)',
 'Les vaccins du PEV (0-5 ans) sont GRATUITS. Le vaccin contre la fièvre jaune est obligatoire pour voyager en Afrique.',
 NULL,
 ARRAY['vaccination', 'vaccin', 'carnet vaccination', 'carte vaccin', 'fievre jaune', 'fièvre jaune', 'PEV'], true, NOW(), NOW()),

(gen_random_uuid(), 'Certificat médical', 'certificat-medical', 'SANTE',
 'Attestation de l''état de santé d''une personne délivrée par un médecin.',
 'Le certificat médical est un document signé par un médecin attestant de l''état de santé d''une personne, pouvant indiquer l''aptitude physique ou un diagnostic.',
 'Requis pour l''emploi, le sport, le permis de conduire, l''admission scolaire, certaines démarches administratives.',
 10000, 'FC', 'Immédiat à 2 jours',
 ARRAY['Carte d''identité', 'Motif de la demande'],
 '1. Se rendre à l''hôpital ou au centre de santé\n2. Consulter un médecin\n3. Subir les examens nécessaires\n4. Le médecin rédige le certificat\n5. Payer les frais de consultation et du certificat',
 'Hôpitaux, cliniques et centres de santé agréés',
 'Certains employeurs ou institutions exigent que le certificat soit délivré par un médecin agréé par l''État.',
 NULL,
 ARRAY['certificat medical', 'certificat médical', 'aptitude physique', 'bilan sante', 'bilan santé', 'medical certificate'], true, NOW(), NOW()),

-- ===================== JUSTICE =====================

(gen_random_uuid(), 'Casier judiciaire (extrait)', 'casier-judiciaire', 'JUSTICE',
 'Document attestant l''existence ou l''absence de condamnations pénales.',
 'L''extrait de casier judiciaire est un document officiel délivré par le greffe du tribunal qui récapitule les condamnations pénales d''une personne, ou atteste de l''absence de condamnation.',
 'Requis pour l''emploi (surtout fonction publique), la naturalisation, certaines licences professionnelles, le voyage.',
 10000, 'FC', '3 à 7 jours',
 ARRAY['Carte d''identité', '2 photos d''identité', 'Demande écrite'],
 '1. Se rendre au greffe du tribunal de grande instance\n2. Remplir le formulaire de demande\n3. Fournir les photos et la pièce d''identité\n4. Payer les frais\n5. Retirer le document après le délai',
 'Greffe du Tribunal de Grande Instance (ex: TGI de Gombe pour Kinshasa)',
 'L''extrait a généralement une validité de 3 mois. Demander le bulletin n°3 (pas de mention des condamnations amnistiées).',
 'Code de procédure pénale congolais',
 ARRAY['casier judiciaire', 'casier', 'extrait casier', 'antecedents judiciaires', 'antécédents judiciaires', 'criminal record', 'bonne vie et moeurs'], true, NOW(), NOW()),

(gen_random_uuid(), 'Attestation de bonne vie et mœurs', 'attestation-bonne-vie', 'JUSTICE',
 'Certificat attestant de la bonne conduite morale d''une personne.',
 'L''attestation de bonne vie et mœurs est un document délivré par la commune certifiant qu''une personne a une bonne conduite et n''a fait l''objet d''aucune plainte dans son quartier.',
 'Complement au casier judiciaire. Requis pour l''emploi, l''obtention de licence, les démarches d''immigration.',
 5000, 'FC', '2 à 5 jours',
 ARRAY['Carte d''identité', 'Attestation de résidence', 'Attestation du chef de quartier'],
 '1. Obtenir une attestation du chef de quartier\n2. Se rendre à la maison communale\n3. Présenter les documents\n4. Payer les frais\n5. Retirer l''attestation signée par le bourgmestre',
 'Maison communale de la commune de résidence',
 'Commencer par le chef de quartier. Le document est généralement valide 3 mois.',
 NULL,
 ARRAY['bonne vie', 'bonne moeurs', 'bonne conduite', 'moralite', 'moralité', 'good conduct', 'bonne vie et moeurs'], true, NOW(), NOW()),

-- ===================== ÉDUCATION =====================

(gen_random_uuid(), 'Diplôme d''État (examen national)', 'diplome-detat', 'EDUCATION',
 'Diplôme de fin d''études secondaires en RDC.',
 'Le Diplôme d''État est le diplôme sanctionnant la fin des études secondaires (6e année secondaire), délivré après réussite de l''examen national organisé par le Ministère de l''Éducation.',
 'Obligatoire pour l''accès à l''université et à l''enseignement supérieur. Requis pour certains emplois.',
 25000, 'FC', '2 à 6 mois après les résultats',
 ARRAY['Carte d''élève', 'Bulletin de 6e année secondaire', 'Acte de naissance', 'Photos d''identité'],
 '1. S''inscrire à l''examen via l''école\n2. Payer les frais d''inscription à l''examen\n3. Passer les épreuves de l''examen d''État\n4. Attendre les résultats\n5. En cas de réussite, retirer le diplôme au bureau de l''éducation',
 'Ministère Provincial de l''Éducation / Inspection de l''enseignement',
 'Conserver l''original en lieu sûr et utiliser des copies certifiées pour les démarches.',
 'Loi-cadre n° 14/004 du 11 février 2014 de l''enseignement national',
 ARRAY['diplome etat', 'diplôme état', 'diplôme d''état', 'examen etat', 'examen état', 'examen national', 'baccalaureat', 'baccalauréat', 'fin secondaire'], true, NOW(), NOW()),

(gen_random_uuid(), 'Équivalence de diplôme', 'equivalence-diplome', 'EDUCATION',
 'Procédure de reconnaissance d''un diplôme étranger en RDC.',
 'L''équivalence de diplôme est la reconnaissance officielle de la valeur d''un diplôme obtenu à l''étranger par rapport au système éducatif congolais.',
 'Nécessaire pour utiliser un diplôme étranger en RDC (emploi, études supérieures, concours).',
 50000, 'FC', '1 à 3 mois',
 ARRAY['Diplôme original et copie certifiée', 'Relevés de notes', 'Acte de naissance', 'Carte d''identité', 'Traduction certifiée (si diplôme en langue étrangère)'],
 '1. Déposer le dossier au Ministère de l''Enseignement Supérieur\n2. Payer les frais de traitement\n3. Service étudie le dossier\n4. Commission d''équivalence statue\n5. Retirer l''attestation d''équivalence',
 'Ministère de l''Enseignement Supérieur et Universitaire',
 'Garder les relevés de notes originaux. Le processus peut prendre du temps — démarrer tôt.',
 NULL,
 ARRAY['equivalence', 'équivalence', 'diplome etranger', 'diplôme étranger', 'reconnaissance diplome'], true, NOW(), NOW()),

-- ===================== IMPÔTS & TAXES =====================

(gen_random_uuid(), 'Numéro Impôt (NIF)', 'numero-impot-nif', 'IMPOTS',
 'Numéro d''identification fiscale attribué aux contribuables.',
 'Le Numéro Impôt (NIF) est un identifiant unique attribué par la DGI à tout contribuable (personne physique ou morale) exerçant une activité économique en RDC.',
 'Obligatoire pour toute activité commerciale, déclaration fiscale, ouverture de compte professionnel, marchés publics.',
 20000, 'FC', '1 à 2 semaines',
 ARRAY['Carte d''identité', 'RCCM (pour les entreprises)', 'Statuts notariés (pour les sociétés)', 'Attestation de résidence ou domicile professionnel'],
 '1. Se rendre au CDI (Centre des Impôts) de sa juridiction\n2. Remplir le formulaire de demande\n3. Fournir les documents requis\n4. Payer les frais d''attribution\n5. Retirer le NIF après traitement',
 'Direction Générale des Impôts (DGI) / Centre des Impôts',
 'Le NIF est obligatoire même pour les petits commerçants. Il doit figurer sur toutes les factures.',
 'Loi n° 004/2003 du 13 mars 2003 portant réforme des procédures fiscales',
 ARRAY['NIF', 'numero impot', 'numéro impôt', 'identifiant fiscal', 'impot', 'impôt', 'taxe', 'fiscal', 'DGI'], true, NOW(), NOW()),

(gen_random_uuid(), 'Patente (licence d''exploitation)', 'patente', 'IMPOTS',
 'Taxe annuelle sur l''exercice d''une activité commerciale ou professionnelle.',
 'La patente est une contribution annuelle payée par toute personne exerçant une activité commerciale, industrielle ou professionnelle. Elle donne droit à exercer légalement.',
 'Autorisation légale d''exercer une activité économique. Son absence entraîne des sanctions et la fermeture.',
 50000, 'FC', 'Immédiat après paiement',
 ARRAY['NIF', 'RCCM', 'Carte d''identité du gérant', 'Attestation de localisation commerciale'],
 '1. Se rendre au bureau des recettes de la DGRK\n2. Présenter le NIF et le RCCM\n3. Déclarer le type d''activité\n4. Payer le montant de la patente (varie selon l''activité)\n5. Recevoir le certificat de patente',
 'DGRK / Bureau des recettes communales',
 'Le montant dépend de la taille et du type d''activité. À renouveler chaque année.',
 NULL,
 ARRAY['patente', 'licence exploitation', 'autorisation commerce', 'commerce', 'exercer'], true, NOW(), NOW()),

(gen_random_uuid(), 'RCCM (Registre de Commerce)', 'rccm', 'JUSTICE',
 'Immatriculation au Registre du Commerce et du Crédit Mobilier.',
 'Le RCCM est le registre officiel dans lequel est immatriculé tout commerçant ou société exerçant une activité en RDC. Le numéro RCCM identifie l''entreprise.',
 'Obligatoire pour exercer légalement. Requis pour l''obtention du NIF, les marchés publics, les contrats commerciaux.',
 50000, 'FC', '1 à 2 semaines',
 ARRAY['Carte d''identité du gérant', 'Statuts notariés de la société', 'Attestation de siège social', 'Frais de dépôt'],
 '1. Rassembler les statuts notariés\n2. Se rendre au greffe du Tribunal de Commerce (TRICOM)\n3. Remplir le formulaire d''immatriculation\n4. Payer les frais\n5. Retirer le numéro RCCM\n6. Publier au Journal Officiel (pour les SARL et SA)',
 'Greffe du Tribunal de Commerce de Kinshasa/Gombe',
 'Le RCCM est la première étape de la création d''entreprise en RDC. Ensuite vient le NIF et la patente.',
 'Acte uniforme OHADA relatif au droit commercial général',
 ARRAY['RCCM', 'registre commerce', 'registre du commerce', 'immatriculation entreprise', 'creation entreprise', 'création entreprise', 'societe', 'société'], true, NOW(), NOW()),

-- ===================== SÉCURITÉ =====================

(gen_random_uuid(), 'Déclaration de perte', 'declaration-de-perte', 'SECURITE',
 'Document officiel attestant la perte de documents ou d''objets.',
 'La déclaration de perte est un procès-verbal établi au commissariat de police attestant qu''une personne a perdu un document officiel (carte d''identité, permis, etc.) ou un objet de valeur.',
 'Nécessaire pour demander le remplacement de tout document officiel perdu (carte d''identité, permis de conduire, passeport, etc.).',
 5000, 'FC', 'Immédiat',
 ARRAY['Carte d''identité (ou tout autre document d''identification)', 'Description détaillée de l''objet/document perdu'],
 '1. Se rendre au commissariat de police le plus proche\n2. Expliquer les circonstances de la perte\n3. L''agent rédige le procès-verbal\n4. Payer les frais\n5. Recevoir une copie de la déclaration',
 'Commissariat de police de la commune de résidence',
 'Faire la déclaration le plus tôt possible après la perte. Conserver la déclaration pour les démarches de remplacement.',
 NULL,
 ARRAY['declaration perte', 'déclaration perte', 'perte document', 'perdu', 'document perdu', 'vol document'], true, NOW(), NOW()),

(gen_random_uuid(), 'Attestation de plainte', 'attestation-de-plainte', 'SECURITE',
 'Document certifiant le dépôt d''une plainte auprès de la police.',
 'L''attestation de plainte est un document officiel délivré par le commissariat confirmant qu''une personne a déposé une plainte pour un fait précis (vol, agression, escroquerie, etc.).',
 'Preuve du dépôt de plainte. Utile pour les recours judiciaires, les assurances, et la protection juridique.',
 5000, 'FC', 'Immédiat',
 ARRAY['Carte d''identité', 'Preuves éventuelles (photos, documents)'],
 '1. Se rendre au commissariat compétent\n2. Expliquer les faits détaillés\n3. L''officier de police judiciaire rédige le PV\n4. Signer le PV\n5. Recevoir l''attestation de plainte',
 'Commissariat de police / Sous-commissariat',
 'Demander une copie signée et cachetée. Noter le numéro du PV pour le suivi.',
 NULL,
 ARRAY['plainte', 'deposer plainte', 'déposer plainte', 'vol', 'agression', 'escroquerie', 'PV police'], true, NOW(), NOW()),

-- ===================== SOCIAL =====================

(gen_random_uuid(), 'Carte INSS (sécurité sociale)', 'carte-inss', 'SOCIAL',
 'Carte d''affiliation à l''Institut National de Sécurité Sociale.',
 'La carte INSS est le document attestant l''affiliation d''un travailleur salarié à la sécurité sociale congolaise, gérée par l''INSS.',
 'Donne droit aux prestations sociales : pension de retraite, allocations familiales, risques professionnels.',
 0, 'FC', '2 à 4 semaines',
 ARRAY['Contrat de travail', 'Carte d''identité', 'Photos d''identité', 'Attestation de l''employeur'],
 '1. L''employeur déclare le travailleur à l''INSS\n2. Remplir le formulaire d''affiliation\n3. Fournir les documents\n4. L''INSS délivre le numéro d''affiliation\n5. Retirer la carte INSS',
 'Agences INSS (Institut National de Sécurité Sociale)',
 'C''est l''employeur qui est tenu de faire l''affiliation. Vérifier que votre employeur vous a bien déclaré.',
 'Décret-loi du 29 juin 1961 organique de la sécurité sociale',
 ARRAY['INSS', 'securite sociale', 'sécurité sociale', 'pension', 'retraite', 'allocations familiales', 'social'], true, NOW(), NOW()),

(gen_random_uuid(), 'Carte de demandeur d''emploi (ONEM)', 'carte-onem', 'SOCIAL',
 'Carte d''enregistrement comme demandeur d''emploi.',
 'La carte de demandeur d''emploi est délivrée par l''ONEM (Office National de l''Emploi) aux personnes en recherche d''emploi.',
 'Officialise le statut de demandeur d''emploi. Peut donner accès à des formations professionnelles et à des offres d''emploi.',
 5000, 'FC', '1 à 2 semaines',
 ARRAY['Carte d''identité', 'Diplômes (copies)', 'CV', 'Photos d''identité'],
 '1. Se rendre à l''antenne ONEM la plus proche\n2. Remplir le formulaire d''inscription\n3. Fournir les documents\n4. Payer les frais\n5. Retirer la carte de demandeur d''emploi',
 'Bureaux de l''ONEM (Office National de l''Emploi)',
 'S''inscrire tôt après la fin des études. L''ONEM organise aussi des formations gratuites.',
 NULL,
 ARRAY['ONEM', 'demandeur emploi', 'chercher travail', 'emploi', 'chomage', 'chômage', 'travail'], true, NOW(), NOW());
